[package]
name = "oasysdb"
version = "0.7.2"
edition = "2021"
license = "Apache-2.0"
readme = "readme.md"

# Information.
authors = ["Edwin Kys", "Oasys"]
description = "Hybrid vector store with SQL integration & multi-index support."
homepage = "https://docs.oasysdb.com"
repository = "https://github.com/oasysai/oasysdb"

# Metadata.
keywords = ["embedded", "vector", "database", "search", "anns"]
categories = ["database", "algorithms", "embedded"]

[dependencies]
uuid = { version = "1.9.1", features = ["v4", "fast-rng", "serde"] }
half = { version = "2.4.1", features = ["serde"] }
tokio = { version = "1.39.2", features = ["rt-multi-thread"] }
url = "2.5.2"
futures = "0.3.30"
rand = "0.8.5"

# Parallelism.
simsimd = { version = "4.4.0", optional = true }
rayon = "1.10.0"

# Serialization.
serde = { version = "1.0.203", features = ["derive"] }
bincode = "1.3.3"
serde_json = "1.0.120"

[dependencies.sqlx]
version = "0.7.4"
default-features = false
features = ["all-databases", "runtime-tokio"]

[dev-dependencies]
byteorder = "1.5.0"
curl = "0.4.44"
flate2 = "1.0.30"
tar = "0.4.41"

[features]
default = ["simd"]
simd = ["dep:simsimd"]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
