[package]
name = "oasysdb"
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
readme = "readme.md"

# Information.
authors = ["Edwin Kys", "Oasys"]
description = "Fast & scalable vector store with ground-up hybrid ANN search support."
homepage = "https://docs.oasysdb.com"
repository = "https://github.com/oasysai/oasysdb"

# Metadata.
keywords = ["vector", "database", "anns", "search", "simd"]
categories = ["database", "algorithms", "data-structures"]

[dependencies]

[dev-dependencies]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
