[package]
name = "oasysdb"
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
readme = "readme.md"

# Information.
authors = ["Edwin Kys", "Oasys"]
description = "Fast & scalable vector store with ground-up hybrid ANN search support."
homepage = "https://docs.oasysdb.com"
repository = "https://github.com/oasysai/oasysdb"

# Metadata.
keywords = ["vector", "database", "anns", "search", "simd"]
categories = ["database", "algorithms", "data-structures"]

[dependencies.tokio]
version = "1.38.0"
features = ["macros", "rt-multi-thread"]

[dependencies]
arrow = "52.0.0"
arrow-schema = { version = "52.0.0", features = ["serde"] }
rayon = "1.10.0"
regex = "1.10.5"
uuid = { version = "1.9.1", features = ["v4", "rng"] }

# gRPC stuff.
prost = "0.12.6"
tonic = "0.11.0"

# Serialization.
serde = { version = "1.0.203", features = ["derive"] }
bincode = "1.3.3"

[build-dependencies]
tonic-build = "0.11.0"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
