[package]
name = "oasysdb"
version = "0.8.0"
edition = "2021"
authors = ["Edwin Kys"]

[dependencies]
tokio = { version = "1.39.3", features = ["rt-multi-thread", "macros"] }
rand = "0.8.5"
clap = "4.5.16"

# gRPC-related dependencies
tonic = "0.12.1"
prost = "0.13.1"

# Serialization-related dependencies
serde = { version = "1.0.208", features = ["derive"] }

# Parallelism-related dependencies
simsimd = "5.0.1"
rayon = "1.10.0"

[dependencies.sqlx]
version = "0.8.0"
default-features = false
features = ["postgres", "runtime-tokio"]

[build-dependencies]
tonic-build = "0.12"
