[package]
name = "oasysdb"
version = "0.8.0"
edition = "2021"
authors = ["Edwin Kys"]

[workspace]
members = ["servers/coordinator", "servers/data"]

[lib]
name = "oasysdb"
path = "src/lib.rs"

[dependencies]
simsimd = "5.0.1"

# Serialization-related dependencies
serde = { version = "1.0.208", features = ["derive"] }
