name: Publish documentation website

on:
  workflow_dispatch:

  push:
    branches:
      - main

    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Publish the documentation
        run: |
          mkdocs gh-deploy --force --message "cd: deployed docs changes from {sha} commit"
